### ISSUE TITLE
这个方法判断定位权限走不通

### ISSUE THREAD

**Issue by pandavickey** [jokermonn/permissions4m#13]
你好，非常欣喜能看到你这样适配国内厂商的定位权限，我比较关注定位权限这一块，因为我们对APP定位权限要求比较高，而我利用系统的权限校验通常在国内厂商上不准确，看到你的逻辑是获取到了权限之后再调一次getLastKnownLocation，如果返回null说明还是没有给权限，初看之下这个逻辑非常惊喜，但是看了官方文档后发现有一种情况规避不了，那就是把GPS关掉它也会返回null。

Returns a Location indicating the data from the last known location fix obtained from the given provider.
This can be done without starting the provider. Note that this location could be out-of-date, for example if the device was turned off and moved to another location.
**If the provider is currently disabled, null is returned.**

所以这个判断还是不准确的，还是考虑下有没有别的途径。多谢你的分享。

**Comment by pandavickey** [comment]
locationManager.isProviderEnabled("gps"); 可以再加一个GPS是否打开的判断，这样可行？

**Comment by jokermonn** [comment]
艾玛，我就说为什么魅族定位上总是时而有时而无的，原来问题就在这！感谢老铁，明日之内上新版本！

**Comment by pandavickey** [comment]
哈哈哈哈

**Comment by jokermonn** [comment]
老铁给个思路，我现在的想法是， `locationManager.isProviderEnabled("gps");` 是 true，那么就说明 GPS 打开了，肯定 `return true`。但是这个不为 true 的情况就不好判断了， `locationManager.getProviders(true);` 有些是 `GPS`、`NETWORK `、`PASSIVE_PROVIDER `，有些是 `NETWORK `、`PASSIVE_PROVIDER `，而且 `ocationManager.getLastKnownLocation()` 都为 null

**Comment by pandavickey** [comment]
/**
     * @param context
     * @return
     * @throws Exception
     */
    public static final boolean isGpsOpen(Context context) throws Exception {
        LocationManager locationManager = (LocationManager) context.getSystemService("location");
        boolean enabled = locationManager.isProviderEnabled("gps");
        String providers = Settings.Secure.getString(context.getContentResolver(), "location_providers_allowed");
        return enabled || providers.contains("gps");
    }

我是通过这个方法判断有没有打开GPS的，没有打开GPS，我返回了默认true，因为这种情况下我无法判断。

**Comment by jokermonn** [comment]
经测试，决定采用以下方法：

        granted = false;
        final LocationManager locationManager = (LocationManager) activity.getSystemService(Context
                .LOCATION_SERVICE);
        List<String> list = locationManager.getProviders(true);
        if (list.contains(LocationManager.GPS_PROVIDER)) {
            return true;
        } else if (list.contains(LocationManager.NETWORK_PROVIDER)) {
            return true;
        } else {
            locationManager.requestLocationUpdates(LocationManager.GPS_PROVIDER, 0L, 0F, new
                    LocationListener() {
                        @Override
                        public void onLocationChanged(Location location) {
                            locationManager.removeUpdates(this);
                        }

                        @Override
                        public void onStatusChanged(String provider, int status, Bundle extras) {
                            locationManager.removeUpdates(this);
                            granted = true;
                        }

                        @Override
                        public void onProviderEnabled(String provider) {
                            locationManager.removeUpdates(this);
                        }

                        @Override
                        public void onProviderDisabled(String provider) {
                            locationManager.removeUpdates(this);
                        }
                    });
            return granted;
        }

对于方法 `locationManager.getProviders(true);` 返回的 list 中可能包含 gps, network, passive 中的任意一种或多种，如果返回 gps 或 network 中的一种或多种说明当前应用是一定拿到了权限的。但是如果不返回就代表未拿到权限吗？实际上不然，在 oppo 部分机型和我的 nexus 6p （不排除其他机型也会有这样的问题）在未打开 gps 的情况下也是给一个空的 list 的，但是此时通过 `locationManager.requestLocationUpdates()` 方法是可以拿到相应的值并回调 `onStatusChanged()` 方法的，所以我们需要在 `onStatusChanged()` 中做判断。目前是这样
