### ISSUE TITLE
不能用在module里面

### ISSUE THREAD

**Issue by Marlborn** [jokermonn/permissions4m#14]
这个不能用在module里面,只能用在app中,
用在module里 java.lang.NullPointerException: Attempt to invoke interface method 'void com.joker.api.wrapper.AnnotationWrapper$PermissionsProxy.granted(java.lang.Object, int)' on a null object reference
有什么办法可以放在下层module的gradle中吗?

**Comment by jokermonn** [comment]
demo 不就是以 module 形式出现的吗

**Comment by Marlborn** [comment]
我的意思是把compile 'com.github.jokermonn:permissions4m:2.1.1-lib'
annotationProcessor 'com.github.jokermonn:permissions4m:2.1.1-processor'写在下面的module的gradle中,demo是写在app的gradle的啊

**Comment by jokermonn** [comment]
能理解了，但是我没试过，不知道怎么去解决，可能是因为编译时注解生成的代理类不是生在 module 中的，所以不能找到该类，如果是这样的话，解决方法就是不要使用注解，而是使用 listener

**Comment by Marlborn** [comment]
是的了 如果依赖不写在app的gradle中只能用listener了,用注解那个就报错了,用listener是可以的.
