### ISSUE TITLE
小米手机自动禁止权限如何解决？

### ISSUE THREAD

**Issue by WhoIsAA** [jokermonn/permissions4m#15]
在小米手机中会自动禁用一些权限，例如修改短信、通知类短信、读取联系人等权限，但回调的却是permissionGranted申请成功，这个该如何解决，感谢～

**Comment by jokermonn** [comment]
请问您的小米版本、型号是？

**Comment by WhoIsAA** [comment]
小米5S、红米4X都有这个问题，通知类短信这个应该是MIUI自己独有的权限，可以忽略，但是读取联系人这个权限我有去申请，回调显示成功，但过了五六秒通知栏则显示自动禁用读取联系人权限

**Comment by jokermonn** [comment]
您的小米是否开启了 miui 优化、手机中是否存在联系人？

**Comment by WhoIsAA** [comment]
没开启MIUI优化，手机中有联系人

**Comment by WhoIsAA** [comment]
刚开启了MIUI优化卸载App重新装了，还是有一样的问题，系统自动禁止了修改短信、修改联系人权限，这个问题都是在App第一次安装启动时出现，第二次运行就没问题了

**Comment by jokermonn** [comment]
您这么一说我有点印象了，实际上 permissions4m 在请求联系人权限的时候是这样的一个流程：原生请求 -> 原生请求返回为 true -> 查询数据库是否真的能拿到联系人。这样的过程在第一次的时候因为用户还有没选择是否拒绝权限（dialog 和查询数据库是异步操作），是能够拿到联系人的，但是第二次小米已经明确禁止的时候，是拿不到联系人的

**Comment by WhoIsAA** [comment]
那我是要用同步申请多个权限？
顺便问下哈，我现在有个需求是获取读取短信、读取彩信、读取联系人等权限成功后，才去执行查询本地数据库的操作，如果用permission4m需要通过switch逐个判断，可以提供一个回调方法，告知是否全部权限获取成功吗？或者在用户拒绝了某个权限时，返回一个List表示拒绝了哪个权限

**Comment by jokermonn** [comment]
1.同步申请多个权限，和单个申请权限的结果是一样的
2.针对您所说的需求，目前 permissions4m 并未做相应的接口，我给您的思路是，创建 deniedList 和 grantedList 并在相应的权限的回调方法中添加相应的信息，在最后一个被回调的接口中（按照您上面的需求，应该就是读取联系人）的回调方法中就可以获取到那些权限被拒绝了，那些权限被同意了
3.您的这个需求很棒，后期考虑添加进 permissions4m

**Comment by WhoIsAA** [comment]
如果可以公开一个方法，去check下还有哪些权限未被允许的就好了，例如我跳转设置页面允许了某个权限，可能会在onActivityResult中检查下该权限是否被允许...
