### ISSUE TITLE
For M 是否可以考虑去掉？

### ISSUE THREAD

**Issue by rantianhua** [jokermonn/permissions4m#2]
具体的权限检查是针对M及以上，但事实上国内手机在M以下，也自己整了一套权限管理。比如魅蓝2，ContextCompat.checkSelfPermission() 也只是检查Manifest里面有没有声明权限，而实际上，比如录音，在真正开始录音的时候才弹出一个系统的权限申请框。所以建议针对锅内手机的话，For M其实没有意义，干脆取消版本的控制。

**Comment by jokermonn** [comment]
我这样认为，其一—— permissions4m 当然不只是针对国内手机，也要针对国内的非国产手机。其二——我觉得好的解决方法是，针对小米、魅族这种低于 M 版本也有权限申请的手机做 >= 某个版本时就会有权限申请，而针对非类手机就做 >= M 就会有权限申请。如果您那边能提供一下魅族的具体信息，例如：

- 是所有魅族手机在某个版本以上都会有权限申请吗？还是说只有特定机型，如果是特定机型的话，您手上有哪些机型是这样的情况？
- 是从哪个版本才开始有权限申请的

**Comment by rantianhua** [comment]
确实，你说的也是有道理的，不过考虑到设计的机型千奇百怪，要做一套适配到所有机型的方案，成本比较大，而且就算完成了，维护成本也很高。所以我建议的就是这种最简单暴力的方式，缺点可能就是暴力了点儿，但稳定性能更高，成本也能降低很多。

> 是所有魅族手机在某个版本以上都会有权限申请吗？还是说只有特定机型，如果是特定机型的话，您手上有哪些机型是这样的情况？

我不能保证所有的魅族手机版本都这样，我只是说我的魅族手机的情况（穷逼只有一个手机....）。我测试的手机机型是魅蓝2，Android 版本：5.1，Flyme 版本：Flyme OS 4.5.3.2C。

> 是从哪个版本才开始有权限申请的

抱歉，这个我也无法回答，没有用过所有版本的魅族。

**Comment by jokermonn** [comment]
已适配魅族 5.0+，可帮忙测试啦，谢谢

**Comment by rantianhua** [comment]
录音权限在手机上已经生效。
